### ISSUE TITLE
Incorrect Decoding when running Dart in Browser Environment

### ISSUE THREAD

**Issue by sterlingwellscaffeine** [C0MM4ND/dart_fast_base58#2]
How to reproduce: 
- Run the Base58Decode function on a string in a browser environment
- This will cause the code to compile into JS
- The output will only return the last four bytes instead of the entire result. 

This makes this library unusable in cross-platform dart applications.

**Comment by c0mm4nd** [comment]
resolved in `v0.2.1`. Thanks for your report!
